// Generated by Wrangler on Fri May 10 2024 10:45:03 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	UPSTASH_KAFKA_REST_URL: string;
	UPSTASH_KAFKA_REST_USERNAME: string;
	UPSTASH_KAFKA_REST_PASSWORD: string;
}
